### ISSUE TITLE
Strange IndexOutOfBounceException

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#17]
When exporting the dataset from #16 I occasionally get the following Exception:

```
Caused by: org.gecko.emf.exporter.EMFExportException: org.gecko.emf.exporter.EMFExportException: java.lang.IndexOutOfBoundsException: Column is greater than range size
	at org.gecko.emf.exporter.ods.EMFODSExporter.exportResourceTo(EMFODSExporter.java:112)
	at org.gecko.emf.ods.configuration.EMFODSResource.doSave(EMFODSResource.java:56)
	... 62 more
Caused by: org.gecko.emf.exporter.EMFExportException: java.lang.IndexOutOfBoundsException: Column is greater than range size
	at org.gecko.emf.exporter.ods.EMFODSExporter.exportEObjectsTo(EMFODSExporter.java:185)
	at org.gecko.emf.exporter.ods.EMFODSExporter.exportResourceTo(EMFODSExporter.java:109)
	... 63 more
Caused by: java.lang.IndexOutOfBoundsException: Column is greater than range size
	at com.github.miachm.sods.Range.getCell(Range.java:88)
	at org.gecko.emf.exporter.ods.EMFODSExporter.setStringValueCell(EMFODSExporter.java:872)
	at org.gecko.emf.exporter.ods.EMFODSExporter.createSheetData(EMFODSExporter.java:438)
	at org.gecko.emf.exporter.ods.EMFODSExporter.createSheetData(EMFODSExporter.java:383)
	at org.gecko.emf.exporter.ods.EMFODSExporter.createSheetDataForEObjectWithEReferences(EMFODSExporter.java:311)
	at org.gecko.emf.exporter.ods.EMFODSExporter.createSheetsData(EMFODSExporter.java:281)
	at org.gecko.emf.exporter.ods.EMFODSExporter.exportEObjectsTo(EMFODSExporter.java:168)
	... 64 more
```

It is rather strange, as it seems to be rather random. Yesterday I had it everytime and I thought this to be a general problem. As I reran today, It surprisingly worked without the Exception until after a few tries it didn't.

**Comment by ideas-into-software** [comment]
@juergen-albert

Please refer to PR https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/18 for up-to-date info.

**Comment by ideas-into-software** [comment]
Closing as https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/18 is merged
